# Generated by Django 4.1.5 on 2023-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
