# Generated by Django 4.1.5 on 2023-01-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
