# Generated by Django 4.1.5 on 2023-01-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MangaGenres',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('own_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.mangavolume')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.mangagenres'),
        ),
    ]
