# Generated by Django 4.1.5 on 2023-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='news-title', max_length=50)),
                ('text', models.TextField(blank=True, default='news', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
