# Generated by Django 4.1.5 on 2023-01-15 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanfic', '0002_fanficpage_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanficLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='fanfic.fanfic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
