# Generated by Django 4.1.5 on 2023-01-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeGenres',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(blank=True, default='Other', on_delete=django.db.models.deletion.SET_DEFAULT, to='anime.animegenres'),
        ),
    ]
