# Generated by Django 4.1.5 on 2023-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_fanficpage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='date_created',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
